import { defineType } from 'sanity'

export default defineType({
  type: 'object',
  name: 'narrativePublish',
  title: 'Narrative Publish',
  fields: [
    {
      type: 'string',
      title: 'Post ID',
      name: 'postId',
      description: 'Paste the Post ID generated by Narrative Publish',
    },
  ],
  preview: {
    select: {
      postId: 'postId',
    },
    prepare({ postId }) {
      return {
        title: 'Narrative Publish',
        subtitle: postId,
      }
    },
  },
})
